name: Publish Packages

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: |
          npm install
          cd lambda && npm install

      - name: Generate Bindings For All Languages
        run: npm run package

      - name: Publish to npm
        run: npm run publish:npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to Maven
        run: npm run publish:maven
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          MAVEN_GPG_PRIVATE_KEY_PASSPHRASE: ${{ secrets.MAVEN_GPG_PRIVATE_KEY_PASSPHRASE }}
          MAVEN_STAGING_PROFILE_ID: ${{ secrets.MAVEN_STAGING_PROFILE_ID }}
          MAVEN_ENDPOINT: https://s01.oss.sonatype.org

      - name: Publish to NuGet
        run: npm run publish:nuget
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish to Golang
        run: npm run publish:golang
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_USER_NAME: ilkrklc
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}

      - name: Publish to PyPI
        run: npm run publish:pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
